### ISSUE TITLE
Getting the thumbnail url is not working

### ISSUE THREAD

**Issue by EmpujateEste** [JustalK/PORNHUB-API#1]

**Comment by JustalK** [comment]
Hello,

Oh ! Nice catching it. I made an error in the documentation.
I updated it.

use the parameter : `thumbnail_url`

```
const pornhub = require('@latsuj/pornhub-api');
const video = await pornhub.page(url, ['thumbnail_url']);
```

Thank for the issue ;)
Tell me if any problem.
