### ISSUE TITLE
@latsuj should be @justalk

### ISSUE THREAD

**Issue by EmpujateEste** [JustalK/PORNHUB-API#2]
And only index.js, LICENSE, opt.js, package.js, and README.md are downloaded when running “npm install @justalk/pornhub-api”
Thanks for resolving the previous issue quickly

**Comment by JustalK** [comment]
Hello,

Thank you for finding those errors.
I changed my name account recently and did not spotted that.
I modified the documentation to the package name @justalk

I also modify the whitelist inside the package.json so now the command `npm install @justalk/pornhub-api` should be able to download the right files.
