### ISSUE TITLE
Search all models with parametr "x"

### ISSUE THREAD

**Issue by jhnyjohny** [JustalK/PORNHUB-API#39]
Hello Justalk,

I have such usecase - for example, I want to find all models with height > 180 cm.
Or, if we make things more simple, with height === 180 cm.

Am I right - it's impossible in current implementation, or I miss something?

**Comment by JustalK** [comment]
Hello jhnyjohny,

I dont think it can be done with how pornhub is built.
The `height` belong to the details of a pornstar and there is no filter on their server for doing that.
I need pornhub to have the feature for using it.
