### ISSUE TITLE
Random search result

### ISSUE THREAD

**Issue by sghosh1810** [JustalK/PORNHUB-API#42]
Hello Justalk,

Anyway to get random search results when I search video/gifs whatever?

**Comment by JustalK** [comment]
Merry Christmas !

If I understand correctly, you are asking for a way to get a random page in the search of gif and video ?
It's not possible right now but I can do that in the week. So you will  have that before 27 December.

**Comment by sghosh1810** [comment]
Awesome 👍

**Comment by Lerbiq** [comment]
Is this feature coming? I tried the ph.com/random but that doesn't seem to work.

**Comment by JustalK** [comment]
Sorry, not yet.
It plans but I am right now busy by something. As soon as I finish, I will be working back on this.
