### ISSUE TITLE
does not work with some urls when getting "download_urls"

### ISSUE THREAD

**Issue by BeneathCloud** [JustalK/PORNHUB-API#44]
Thank you for your great work, it's a very nice library!

**Describe the bug**
I found it does work with most urls, but doesn't work with some others.

**To Reproduce**
For example, this particular url: `https://jp.pornhub.com/view_video.php?viewkey=ph5fe73278a9118`

It works well when just getting "title":
```javascript
const pornhub = require('@justalk/pornhub-api');
const url = 'https://jp.pornhub.com/view_video.php?viewkey=ph5fe73278a9118'
const video = await pornhub.page(url, ['title');
```
But if with the "download_urls", it will give me a `'An error occured'` error:
```javascript
const video = await pornhub.page(url, ['title', 'download_urls']);
```

It seems there are some problems with the `download_urls`.

**Comment by JustalK** [comment]
Hello BeneathCloud,

I have seen your message. I will try to look at it.
I am unfortunately a lot busy at the moment between my daughter (I am a father since few month <3) and my work.

I will try to look at it in the next few days.
Sorry for the inconvenience.
I let aside this project for too long. I will be back on it.

**Comment by JustalK** [comment]
It might be link to this one : https://github.com/JustalK/PORNHUB-API/issues/43
So I will fix it together ;)

**Comment by BeneathCloud** [comment]
Warmest congratulations for you and your daughter! I don't have a daughter but I can imagine how busy you are :D  Just follow your own pace ~
 
(and just a little complementary information: the #43 where m3u8 file get downloaded, I can convert it to a mp4 file by using a m3u8-to-mp4 library.)

**Comment by JustalK** [comment]
I have fixed something on the download part, I will try that on your bug tomorrow ;)

**Comment by guiyuanju** [comment]
Thank you~~ I can download it now
